name: release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
          
      - name: Print go tool dist list
        run: go tool dist list

      - name: Build
        run: |
          platforms=("linux/amd64" "darwin/amd64" "windows/amd64")
          for x in "${platforms[@]}"; do
            os=${x%%/*}
            arch=${x##*/}
            filename=${{ github.event.repository.name }}-$os-$arch
            if [ "$os" == "windows" ]; then
              filename+=".exe"
            fi
            GOOS=$os GOARCH=$arch CGO_ENABLED=0 go build -o dist/$filename -trimpath -ldflags "-s -w"
          done
          cd dist
          find ./* -maxdepth 0 -executable -type f -print0 | xargs -0 -I {} echo "sha1sum {} | awk '{print \$1;}' > {}.sha1" | sh
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: |
            dist/*

