name: release

on:
  release:
    types: [published]

jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
          
      - name: Print go tool dist list
        run: go tool dist list
        
      # linux/amd64, darwin/amd64, windows/386, windows/amd64, linux/arm, linux/arm64, linux/mips, linux/mips64, linux/mips64le, linux/mipsle
        
      - name: Build
        run: |
          go tool dist list | while read x; do
            os=${x%%/*}
            arch=${x##*/}
            filename=${{ github.event.repository.name }}-$os-$arch
            if [ "$os" == "windows" ]; then
              filename+=".exe"
            fi
            GOOS=$os GOARCH=$arch go build -o dist/$filename
          done
      - name: Upload build-artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "./dist/*"
